<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matteo Boyer-Wright &amp; Arthur Lemoine">

<title>UK real estate transactions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="uk_real_estate_files/libs/clipboard/clipboard.min.js"></script>
<script src="uk_real_estate_files/libs/quarto-html/quarto.js"></script>
<script src="uk_real_estate_files/libs/quarto-html/popper.min.js"></script>
<script src="uk_real_estate_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="uk_real_estate_files/libs/quarto-html/anchor.min.js"></script>
<link href="uk_real_estate_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="uk_real_estate_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="uk_real_estate_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="uk_real_estate_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="uk_real_estate_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#technical-warnings" id="toc-technical-warnings" class="nav-link active" data-scroll-target="#technical-warnings">Technical warnings</a></li>
  <li><a href="#research-question-presentation" id="toc-research-question-presentation" class="nav-link" data-scroll-target="#research-question-presentation">Research question presentation</a></li>
  <li><a href="#data-sets-description" id="toc-data-sets-description" class="nav-link" data-scroll-target="#data-sets-description">Data sets description</a>
  <ul class="collapse">
  <li><a href="#first-dataset-micro-level-transaction-data" id="toc-first-dataset-micro-level-transaction-data" class="nav-link" data-scroll-target="#first-dataset-micro-level-transaction-data">First dataset: micro-level transaction data</a></li>
  <li><a href="#second-dataset-macro-level-transaction-data" id="toc-second-dataset-macro-level-transaction-data" class="nav-link" data-scroll-target="#second-dataset-macro-level-transaction-data">Second dataset: macro-level transaction data</a></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data analysis</a>
  <ul class="collapse">
  <li><a href="#time-series-analysis-number-of-transactions" id="toc-time-series-analysis-number-of-transactions" class="nav-link" data-scroll-target="#time-series-analysis-number-of-transactions">Time series analysis: number of transactions</a>
  <ul class="collapse">
  <li><a href="#seasonality-study" id="toc-seasonality-study" class="nav-link" data-scroll-target="#seasonality-study">Seasonality study</a></li>
  <li><a href="#time-series-decomposition-graphical-analysis" id="toc-time-series-decomposition-graphical-analysis" class="nav-link" data-scroll-target="#time-series-decomposition-graphical-analysis">Time series decomposition: graphical analysis</a></li>
  </ul></li>
  <li><a href="#additionnal-analysis-bank-rate-vs.-number-of-transactions" id="toc-additionnal-analysis-bank-rate-vs.-number-of-transactions" class="nav-link" data-scroll-target="#additionnal-analysis-bank-rate-vs.-number-of-transactions">Additionnal analysis: bank rate vs.&nbsp;number of transactions</a></li>
  <li><a href="#time-series-analysis-prices" id="toc-time-series-analysis-prices" class="nav-link" data-scroll-target="#time-series-analysis-prices">Time series analysis: prices</a>
  <ul class="collapse">
  <li><a href="#transaction-prices-distribution" id="toc-transaction-prices-distribution" class="nav-link" data-scroll-target="#transaction-prices-distribution">Transaction prices distribution</a></li>
  <li><a href="#price-evolution-nominal-vs.-real" id="toc-price-evolution-nominal-vs.-real" class="nav-link" data-scroll-target="#price-evolution-nominal-vs.-real">Price evolution: nominal vs.&nbsp;real</a></li>
  </ul></li>
  <li><a href="#geographical-analysis-number-of-transactions" id="toc-geographical-analysis-number-of-transactions" class="nav-link" data-scroll-target="#geographical-analysis-number-of-transactions">Geographical analysis: number of transactions</a>
  <ul class="collapse">
  <li><a href="#aggregated-number-of-transaction-on-the-1995-2023-period" id="toc-aggregated-number-of-transaction-on-the-1995-2023-period" class="nav-link" data-scroll-target="#aggregated-number-of-transaction-on-the-1995-2023-period">Aggregated number of transaction on the 1995-2023 period</a></li>
  <li><a href="#number-of-transactions-vs.-population" id="toc-number-of-transactions-vs.-population" class="nav-link" data-scroll-target="#number-of-transactions-vs.-population">Number of transactions vs.&nbsp;population</a></li>
  </ul></li>
  <li><a href="#geographical-analysis-prices" id="toc-geographical-analysis-prices" class="nav-link" data-scroll-target="#geographical-analysis-prices">Geographical analysis: prices</a>
  <ul class="collapse">
  <li><a href="#average-price-on-the-1995-2023-period" id="toc-average-price-on-the-1995-2023-period" class="nav-link" data-scroll-target="#average-price-on-the-1995-2023-period">Average price on the 1995-2023 period</a></li>
  <li><a href="#a-little-machine-learning-science-clustering-in-theory" id="toc-a-little-machine-learning-science-clustering-in-theory" class="nav-link" data-scroll-target="#a-little-machine-learning-science-clustering-in-theory">A little machine learning science: clustering in theory</a></li>
  <li><a href="#clustering-in-practice" id="toc-clustering-in-practice" class="nav-link" data-scroll-target="#clustering-in-practice">Clustering in practice</a></li>
  <li><a href="#socio-demographics-of-clusters" id="toc-socio-demographics-of-clusters" class="nav-link" data-scroll-target="#socio-demographics-of-clusters">Socio-demographics of clusters</a></li>
  </ul></li>
  <li><a href="#wrapping-up-spatiotemporal-patterns" id="toc-wrapping-up-spatiotemporal-patterns" class="nav-link" data-scroll-target="#wrapping-up-spatiotemporal-patterns">Wrapping-up: spatiotemporal patterns</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a>
  <ul class="collapse">
  <li><a href="#data-loading" id="toc-data-loading" class="nav-link" data-scroll-target="#data-loading">Data loading</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data cleaning</a></li>
  <li><a href="#data-exporting" id="toc-data-exporting" class="nav-link" data-scroll-target="#data-exporting">Data exporting</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">UK real estate transactions</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matteo Boyer-Wright &amp; Arthur Lemoine </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<style>
body {
text-align: justify}
</style>
<section id="technical-warnings" class="level1">
<h1>Technical warnings</h1>
<p>For simplicity, the final databases used in this document are available from: https://www.dropbox.com/scl/fo/9c04715s1hkowsf0vnk70/h?rlkey=7r3x8pm6y9nkcdiusfhmq2ulb&amp;dl=0 We recommend you download this folder and place all files in the “data” folder of your own repository.</p>
<p>/!&nbsp;WARNING: you need to run this chunk because the last released version (0.1.4) introduces a bug leading to the following “Error: arguments have different crs”. You might need to launch a new R session if you used the last version of transformr.</p>
<p>Optionally run this chunk if some of the packages we use are not installed on your computer.</p>
</section>
<section id="research-question-presentation" class="level1">
<h1>Research question presentation</h1>
<p>Through this report, we want to explore the determinants of real estate transactions in England and Wales. We will do so by utilizing a diverse set of variables from a variety of government sources.</p>
<p>In this study, we aim at determining which factors contribute to the variation in the number and the price of real estate transactions in the United Kingdom, and to what extent do the location of the property, interest rate, inflation, average income in the area, population density, and seasonality patterns influences these transactions?</p>
<p>First findings and proposal of further analysis:</p>
<p>There is a clear drop in the number of transactions around the financial crisis of 2008. This was preceded by a stagnation in the average yearly price. The Quantitative Easing starting in 2015 could also explain the price peaking in the same year.</p>
<p>Moreover, The number of transactions plummets in 2020 due to the Covid crisis and is followed by a substantial rebound in 2021. Finally, it seems the year 2023 cannot be taken into account because we are missing data from the last months.</p>
<p>Our future analysis will focus on:</p>
<ol type="1">
<li>Look for seasonality in the evolution of the number of transactions.</li>
<li>Analyse the evolution of the price of transactions.</li>
<li>Producing a geographical analysis of both prices and the number of transactions.</li>
<li>Using machine learning techniques (clustering) to find correlations between socio-demographics factors and our variables of interest.</li>
</ol>
</section>
<section id="data-sets-description" class="level1">
<h1>Data sets description</h1>
<p>We use two main datasets in this study.</p>
<section id="first-dataset-micro-level-transaction-data" class="level2">
<h2 class="anchored" data-anchor-id="first-dataset-micro-level-transaction-data">First dataset: micro-level transaction data</h2>
<p>Our first dataset consists of the description of 28634236 real estate transactions using 17 variables between 1995 and 2023.</p>
<p>The main variables are:</p>
<ol type="1">
<li>price_paid is the sale price stated on the transfer deed.</li>
</ol>
<p>2 and 3) The name of the following variables are self-explanatory:year,month.</p>
<ol start="4" type="1">
<li><p>msoa indicates the Middle Layer Super Output Areas (MSOA), which is a geographic hierarchy designed to improve the reporting of small area statistics in England and Wales. The minimum population is 5000 and the mean is 7200. This is the geographical granularity level that we will use through all our study.</p></li>
<li><p>households refers to the mean household disposable (net) income on an equivalised basis for middle layer super output areas (MSOAs) in England and Wales. Equivalisation is the process of accounting for the fact that households with many members are likely to need a higher income to achieve the same standard of living as households with fewer members.</p></li>
</ol>
</section>
<section id="second-dataset-macro-level-transaction-data" class="level2">
<h2 class="anchored" data-anchor-id="second-dataset-macro-level-transaction-data">Second dataset: macro-level transaction data</h2>
<p>Our second dataset consists of the description of 348 real estate transactions using 6 variables on a monthly basis between 1995 and 2003.</p>
<p>The variables are:</p>
<ol type="1">
<li><p>CPI is the Consumer Price Index in the UK provided by the Office for National Statistics.</p></li>
<li><p>rate is the benchmark interest rate decided by the Bank of England.</p></li>
<li><p>nb_transac is the number of transactions in the UK.</p></li>
<li><p>mean_price is the mean nominal price of all the transactions in the UK.</p></li>
<li><p>real_price is the mean real price of all the transactions in the UK, obtained by deflating the mean nominal price using the CPI.</p></li>
<li><p>date indicates the month and the year for which the data is relevant.</p></li>
</ol>
</section>
</section>
<section id="data-analysis" class="level1">
<h1>Data analysis</h1>
<section id="time-series-analysis-number-of-transactions" class="level2">
<h2 class="anchored" data-anchor-id="time-series-analysis-number-of-transactions">Time series analysis: number of transactions</h2>
<p>Using our main dataset, we have created a time series containing the number of monthly transactions from 1995 to 2023.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This first graph allows us to observe 5 important facts:<br>
1) There is a clear seasonality in the evolution of the number of monthly transactions.<br>
2) The number of sales plunged during the 2008 sub-prime crisis.<br>
3) The first lock down (march 2020) was also synonymous of a large slow-down in the number of transaction.<br>
4) The effect depicted in (4) was quickly followed by a catch-up effect in 2021.<br>
5) The number of sales seems to be quickly falling in 2023.</p>
<p>We will dedicate the next section to the analysis of the seasonality of this time series. Regarding the impact of crisis (sub-prime and COVID-19) on the real estate market, a large literature is already available and we decided not to spend to much time on those topics.</p>
<section id="seasonality-study" class="level3">
<h3 class="anchored" data-anchor-id="seasonality-study">Seasonality study</h3>
<section id="graphical-analysis-1" class="level4">
<h4 class="anchored" data-anchor-id="graphical-analysis-1">Graphical analysis (1)</h4>
<p>Just by studying graphically the time series, we are inclined to conclude that it is highly likely that the number of transactions per month is affected by a seasonality phenomena.</p>
<p>The general pattern is especially clear between 2000 and 2005 for instance. The number of transactions is at its lowest every beginning of a new year, and rises sharply until it reaches its highest point around what is likely the end of spring and the summer (a more rigorous study of the patterns will be done later on). Then it drops dramatically until December, to start the new year at a low point.</p>
<p>However, this graphical analysis in itself is not sufficient to conclude with certainty that the time series has a seasonal trend. We will then proceed with more rigorous tests in order to detect seasonality.</p>
</section>
<section id="testing-for-seasonality-1" class="level4">
<h4 class="anchored" data-anchor-id="testing-for-seasonality-1">Testing for seasonality (1)</h4>
<section id="adf-test-1" class="level5">
<h5 class="anchored" data-anchor-id="adf-test-1">ADF test (1)</h5>
<p>We begin with an Augmented Dickey Fuller test. Even though we are aware that the ADF test is not a seasonality test per se, our idea behind this is that if we are unable to detect stationarity in our initial time series, and then, if after de-trending the seasonality in our time series by using a twelfth difference filter (because we use monthly data), we are able to detect stationarity, we can conclude that we have corrected the time series of its seasonal trend component, and that our initial time series is affected by seasonality.</p>
<p>Formally, the ADF test is a unit root test. Imagine we have a time series model of the following form :</p>
<p><span class="math display">\[ Y_t = \mu + \alpha Y_{t-1} + \epsilon_t \quad \textrm{AR(1)} \]</span></p>
<p>The hypothesis for the simple Dickey-Fuller test would be:</p>
<p><span class="math display">\[ H_0: \alpha = 1 \quad \textrm{versus} \quad H_A: \alpha \neq 1 \]</span></p>
<p>And more generally, for any ARIMA model, we can apply the same principle but including high order regressive process in our model equation using the ADF test, with a model of the form:</p>
<p><span class="math display">\[ Y_t = \mu + \beta t +  \alpha Y_{t-1} + \phi_{1}\Delta Y_{t-1} + \phi_{2}\Delta Y_{t-2} + \quad \textrm{...} \quad + \phi_{p}\Delta Y_{t-p} + \epsilon_t \quad \]</span> Where <span class="math inline">\(\mu\)</span> denotes the drift of the process, and <span class="math inline">\(t\)</span> the trend.</p>
<p>The hypothesis remains the same, and can be understood as:</p>
<p><span class="math display">\[ H_0: \quad \textrm{The time series is non-stationary} \quad \textrm{versus} \quad  H_A: \textrm{The time series is stationary} \]</span> Now to the test. We use the function ‘ur.df’ of the ‘urca’ package to realize the test. Note that we select the relevant time series model (ie which order of lags should we select) by discriminating among different high order regressive process models using the Akaike Information Criterion. We only allow for models up to the twelth order, because we have monthly data. We include a drift but no trend because there does not seem to be a general trend over the whole period when we look at the time series graphically.</p>
<p>The regression and test’s results are:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
   Min     1Q Median     3Q    Max 
-70711  -7451   1253   7124  73720 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  6255.83602 3557.97902   1.758 0.079663 .  
z.lag.1        -0.07758    0.04136  -1.876 0.061609 .  
z.diff.lag1    -0.39888    0.06609  -6.035 4.40e-09 ***
z.diff.lag2    -0.27650    0.06952  -3.977 8.64e-05 ***
z.diff.lag3     0.19506    0.07073   2.758 0.006152 ** 
z.diff.lag4     0.00524    0.07099   0.074 0.941204    
z.diff.lag5    -0.05209    0.06965  -0.748 0.455099    
z.diff.lag6    -0.24462    0.06665  -3.670 0.000284 ***
z.diff.lag7    -0.24955    0.06519  -3.828 0.000155 ***
z.diff.lag8    -0.11886    0.06622  -1.795 0.073621 .  
z.diff.lag9    -0.03255    0.06653  -0.489 0.624953    
z.diff.lag10   -0.04920    0.06659  -0.739 0.460599    
z.diff.lag11   -0.03291    0.06292  -0.523 0.601355    
z.diff.lag12    0.20522    0.05597   3.666 0.000288 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 13510 on 319 degrees of freedom
Multiple R-squared:  0.4217,    Adjusted R-squared:  0.3981 
F-statistic: 17.89 on 13 and 319 DF,  p-value: &lt; 2.2e-16


Value of test-statistic is: -1.8757 1.8264 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.44 -2.87 -2.57
phi1  6.47  4.61  3.79</code></pre>
</div>
</div>
<p>We see that the selected best model according to the AIC is the model going up to the twelfth order. Because our t-stat (round(1.8264357),2) for the <span class="math inline">\(\alpha\)</span> component of the estimated model is lower in absolute value compared to the 5% critical value of the associated distribution (3.79), we fail to reject <span class="math inline">\(H_0\)</span> at the 5% level of significance, ie we cannot conclude that our time series is stationnary.</p>
</section>
</section>
<section id="graphical-analysis-2" class="level4">
<h4 class="anchored" data-anchor-id="graphical-analysis-2">Graphical analysis (2)</h4>
<p>Now let us de-trend the possible seasonal part of the process by applying a twelfth order difference filter.</p>
<p>First, we plot this corrected time series:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Graphically, it seems like we have no seasonal trend anymore. We are unable to visually detect a seasonal pattern.</p>
</section>
<section id="testing-seasonality-2" class="level4">
<h4 class="anchored" data-anchor-id="testing-seasonality-2">Testing seasonality (2)</h4>
<section id="adf-test-2" class="level5">
<h5 class="anchored" data-anchor-id="adf-test-2">ADF test (2)</h5>
<p>Then, we proceed with the ADF test, using again the same method for picking up the appropriate model in terms of regressive process order.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
   Min     1Q Median     3Q    Max 
-83762  -4031   1497   6348  64755 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -497.75048  806.89020  -0.617 0.537774    
z.lag.1        -0.25797    0.06267  -4.116 4.96e-05 ***
z.diff.lag1    -0.34672    0.06876  -5.042 7.87e-07 ***
z.diff.lag2    -0.08945    0.07067  -1.266 0.206552    
z.diff.lag3     0.38765    0.06984   5.551 6.16e-08 ***
z.diff.lag4     0.26472    0.07289   3.632 0.000330 ***
z.diff.lag5     0.12318    0.07409   1.663 0.097430 .  
z.diff.lag6     0.09097    0.07280   1.250 0.212405    
z.diff.lag7     0.04218    0.07207   0.585 0.558823    
z.diff.lag8     0.10660    0.07140   1.493 0.136459    
z.diff.lag9     0.09550    0.07165   1.333 0.183602    
z.diff.lag10    0.06840    0.07172   0.954 0.340952    
z.diff.lag11    0.08625    0.06874   1.255 0.210560    
z.diff.lag12   -0.21722    0.05976  -3.635 0.000326 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 14440 on 307 degrees of freedom
Multiple R-squared:  0.5033,    Adjusted R-squared:  0.4823 
F-statistic: 23.93 on 13 and 307 DF,  p-value: &lt; 2.2e-16


Value of test-statistic is: -4.1161 8.6455 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.44 -2.87 -2.57
phi1  6.47  4.61  3.79</code></pre>
</div>
</div>
<p>Again, we see that the selected best model according to the AIC is the model going up to the twelth order. Because our t-stat (1.8264357) for the <span class="math inline">\(\alpha\)</span> component of the estimated model is now higer in absolute value compared to the 5% critical value of the associated distribution (3.79), we reject <span class="math inline">\(H_0\)</span> at the 5% level of significance, ie we conclude that our time series is now stationnary.</p>
<p>This first test seems to indicate that the number of transactions has a seasonal pattern. However, we are aware that the ADF test is not a proper time series seasonality test. We want to reinforce this first result by using a real seasonality test.</p>
</section>
</section>
<section id="wo-combined-seasonality-test" class="level4">
<h4 class="anchored" data-anchor-id="wo-combined-seasonality-test">WO combined seasonality test</h4>
<p>We use the ‘seastests’ package, developped by Daniel Ollech from the Bundesbank. The package documentation is available at https://cran.r-project.org/web/packages/seastests/seastests.pdf. We realize the Ollech-Webel overall seasonality test that combines result from two seasonality tests, the QS test and the KW-test. The test hypothesis are:</p>
<p><span class="math display">\[ H_0: \quad \textrm{The time series does not have a seasonal trend} \quad \textrm{versus} \quad  H_A: \textrm{The time series has a seasonal trend} \]</span></p>
<p>The results are:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Test used:  WO 
 
Test statistic:  1 
P-value:  2.953193e-14 0 0 
 
The WO - test identifies seasonality</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Test used:  WO 
 
Test statistic:  0 
P-value:  1 1 0.9997651 
 
The WO - test does not identify  seasonality</code></pre>
</div>
</div>
<p>We see that the OW combined seasonality test identifies seasonality in the first time series, but does not identify seasonality in the second time series with a twelth order difference filter. This furthers reinforce our belief that the number of transactions has a seasonal pattern.</p>
</section>
</section>
<section id="time-series-decomposition-graphical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="time-series-decomposition-graphical-analysis">Time series decomposition: graphical analysis</h3>
<p>Now that we believe our time series has a seasonal trend, we want to decompose the initial times series into several components (trend, seasonal and stochastic). Note that we decompose our time series as an additive time series, because when we analyse it graphically, we see that the difference between each year is mainly a difference in the average level of transactions each year, and not much a difference between the amplitude of the change in the number of transactions from one month to another inside a specific year.</p>
<p>Graphically, the decomposition gives us:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Several interesting observations can be made using these graphs.</p>
<p>Looking at the trend, we can decompose it in different periods. The first one would be from 1995 to 2007, with an overall steady rise in the number of transactions. This takes place until the 2008 economic crisis creeps in, with a sharp decline in the trend of the number of transactions. After reaching this lowest point, the trend is mostly constant between 2009 and 2013 and 2015 and 2020, with only a slight increase between 2013 and 2015. We must be careful about interpreting the trend of the time series in the period following the outburst of Covid-19. As the UK was in lockdown, this artificially created a drop in the number of transactions in the first part of 2020, followed by a catch-up until the beginning of 2021. Those events are represented in the trend graph, but cannot be considered as a real trend as it was artificially created. Eventually, the catch-up is followed by a fast decline in the trend until the end of our study period, probably due to the economic slowdown, the high inflation and the resulting interest rates hikes by the Bank of England.</p>
<p>Regarding the stochastic part of the decomposition, we can mainly note the fact that the variance of the random element of the process is steady over the whole period, except between 2020 and 2022 where it rises dramatically. This invites us to be even more cautious when it comes to interpreting the trend of the process in this period, as the amount of unexplained variance in the number of transactions is much more important.</p>
<section id="focus-on-the-seasonality-component" class="level4">
<h4 class="anchored" data-anchor-id="focus-on-the-seasonality-component">Focus on the seasonality component</h4>
<p>Eventually, the seasonal trend can be decomposed into several principal periods each year. Let us graph the seasonal component over only one year to realise such a decomposition.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The first period is from February until July with a fast rise from the lowest point up to the highest point of the year in terms of the number of transactions. Then there is a slight decrease in August and September, and then we stay on an high plateau until the end of the year. If the high seasonal trend from June to September can be explained by the fact that most families try to move in their new homes during the summer holidays such that their children do not have to change school in the middle of the year, the drop in the seasonal trend between December and January is harder to explain.</p>
</section>
</section>
</section>
<section id="additionnal-analysis-bank-rate-vs.-number-of-transactions" class="level2">
<h2 class="anchored" data-anchor-id="additionnal-analysis-bank-rate-vs.-number-of-transactions">Additionnal analysis: bank rate vs.&nbsp;number of transactions</h2>
<p>One of the main explanations for the recent slow-down on the market has been the rise in housing loan rates. We decided to compare side-by-side the evolution of the Bank of England rate (which is a good proxy for the loan rates) and the number of transactions on the 1995-2023 period. The following graph let us see that there is a clear inverse relationship between the Bank of England recent increase in its rate and the plunging number of transactions. However, we fill like this explanation is not totally satisfying as the real estate market seemed to behave normally between 1995 and 2009 whereas rates were at even higher levels than nowadays.</p>
<p>Thus, one could conclude that what really matters is less the level of the bank rate than its direction. In other words, it is not the high levels of bank rates that had a negative impact on the number of transactions, but their fast increase. In fact, people might expect (or at least wait) for a decrease in bank rates before considering buying a new house.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="time-series-analysis-prices" class="level2">
<h2 class="anchored" data-anchor-id="time-series-analysis-prices">Time series analysis: prices</h2>
<section id="transaction-prices-distribution" class="level3">
<h3 class="anchored" data-anchor-id="transaction-prices-distribution">Transaction prices distribution</h3>
<p>The second key variable we are interested in is the price of transactions. First, we observe that the distribution of prices is heavily right-skewed. In fact, 99% of transactions are below 1.13^{6} pounds and, more importantly, 95% of transactions do not exceed 5.5^{5} pounds.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="price-evolution-nominal-vs.-real" class="level3">
<h3 class="anchored" data-anchor-id="price-evolution-nominal-vs.-real">Price evolution: nominal vs.&nbsp;real</h3>
<section id="visual-analysis" class="level4">
<h4 class="anchored" data-anchor-id="visual-analysis">Visual analysis</h4>
<p>If we now look at the evolution of prices since 1995, we can see a very steep increase in the average price of transactions. It is also interesting to note that prices have been a lot more volatile since the COVID-19 crisis.</p>
<p>However, when looking at the real prices, we realise that most of the increase took place between 1995 and 2009. While prices have increased again between 2014 and 2021, it seems they are back to their 2009 level in 2023 (or even a little below).</p>
<p>One additional observation is that the 2008 sub-prime crisis had a greater impact on the number of transactions than on the average price.</p>
<p>Finally, the price decrease which started at the end of 2022 is not only due to the recent high levels of inflation. In fact, both real and nominal prices are affected.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="linear-regression" class="level4">
<h4 class="anchored" data-anchor-id="linear-regression">Linear regression</h4>

<table style="text-align:center">
<caption>
<strong>Linear regression of the average transaction price over time and number of transactions</strong>
</caption>
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
mean_price
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
nb_transac
</td>
<td>
0.026<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.010)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
year
</td>
<td>
12,671.210<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(277.872)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-25,254,912.000<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(560,272.700)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
28
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.988
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.987
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
11,647.590 (df = 25)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
1,061.461<sup>***</sup> (df = 2; 25)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>

</tbody></table>
<p>What we can conclude from this regression is: 1) On average, prices have increases by £12,671 per year 2) While being statistically significant at the 5% level (**), the effect of the number of transactions over price is not economically relevant. In fact, the coefficient is equal to 0.026, meaning that if we were to double the number of transactions (ie, a 100% increase from roughly 100 000 per year to 200 000 per year), the average price of a transaction would increase by £2,600.</p>
</section>
</section>
</section>
<section id="geographical-analysis-number-of-transactions" class="level2">
<h2 class="anchored" data-anchor-id="geographical-analysis-number-of-transactions">Geographical analysis: number of transactions</h2>
<section id="aggregated-number-of-transaction-on-the-1995-2023-period" class="level3">
<h3 class="anchored" data-anchor-id="aggregated-number-of-transaction-on-the-1995-2023-period">Aggregated number of transaction on the 1995-2023 period</h3>
<p>The following map depicts the spatial distribution of the aggregated number of transactions over the 1995-2023 period. Each geographical area corresponds to a local authority.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="number-of-transactions-vs.-population" class="level3">
<h3 class="anchored" data-anchor-id="number-of-transactions-vs.-population">Number of transactions vs.&nbsp;population</h3>
<p>Looking at the number of transactions from a geographical point of view allows us to observe a large discrepancy between regions. However, at this stage of the analysis, we can not draw any further conclusion since the regions in which there were a lot of transactions are also the most populated ones. In fact, 9 of the most populated cities in the UK are among the top 10 local areas in terms of number of transactions (see table below).</p>
<section id="country-level" class="level4">
<h4 class="anchored" data-anchor-id="country-level">Country level</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Top 10 cities with the highest number of transactions between 1995 and 2023</caption>
<colgroup>
<col style="width: 24%">
<col style="width: 33%">
<col style="width: 15%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Local authority</th>
<th style="text-align: right;">Number of transactions</th>
<th style="text-align: right;">Population</th>
<th style="text-align: right;">Rank (population)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Birmingham</td>
<td style="text-align: right;">418 155</td>
<td style="text-align: right;">1 142 494</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leeds</td>
<td style="text-align: right;">380 918</td>
<td style="text-align: right;">809 036</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wiltshire</td>
<td style="text-align: right;">258 990</td>
<td style="text-align: right;">513 411</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">County Durham</td>
<td style="text-align: right;">252 614</td>
<td style="text-align: right;">521 346</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bradford</td>
<td style="text-align: right;">248 721</td>
<td style="text-align: right;">546 976</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sheffield</td>
<td style="text-align: right;">231 459</td>
<td style="text-align: right;">554 401</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bristol, City of</td>
<td style="text-align: right;">228 182</td>
<td style="text-align: right;">471 117</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manchester</td>
<td style="text-align: right;">227 546</td>
<td style="text-align: right;">549 853</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cheshire East</td>
<td style="text-align: right;">218 044</td>
<td style="text-align: right;">400 528</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liverpool</td>
<td style="text-align: right;">200 637</td>
<td style="text-align: right;">484 488</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="zoom-on-london" class="level4">
<h4 class="anchored" data-anchor-id="zoom-on-london">Zoom on London</h4>
<p>It is important to note that since London is divided in not less than 31 local authorities, it does not appear in the preceding table. However, in this period the ‘Greater London’ area accounted for 13 % of the total transactions (exactly 3519255 transactions).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Zooming on the Greater London area, we can see that the number of transactions is quite high (considering the size of each local area) and relatively evenly distributed. In fact, in this region, the average number of transactions is 113524, compared with the national average of 83203. Moreover, as we can see on the map, in most local areas, the number of transactions lied between 100 000 and 150 000 transactions.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When correcting for the population levels, we observe that the number of transactions is more evenly distributed. We can also note that the most attractive regions seem to be the ones one the coasts. On the contrary, the regions around Wales and the Northern territories have, on average, a lower number of transactions.</p>
</section>
</section>
</section>
<section id="geographical-analysis-prices" class="level2">
<h2 class="anchored" data-anchor-id="geographical-analysis-prices">Geographical analysis: prices</h2>
<section id="average-price-on-the-1995-2023-period" class="level3">
<h3 class="anchored" data-anchor-id="average-price-on-the-1995-2023-period">Average price on the 1995-2023 period</h3>
<section id="country-level-visual-analysis" class="level4">
<h4 class="anchored" data-anchor-id="country-level-visual-analysis">Country level visual analysis</h4>
<p>Just as in the first part, we will now have a look at the distribution of the average price of transactions. For this first map, the figures are “raw”. In fact, we did not take into account inflation, nor any other socio-demographic variable. Therefore, this map only depicts the average price of transactions over the whole period.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The figure above demonstrates the depth of the division between London and the rest of the UK when it comes to the average price of transactions. Going a little further, we can regroup the UK in 4 main regions according to the average transaction price:&nbsp; - The greater London area, with the highest average transaction price.<br>
- Midlands and Wales, with the lowest average transaction price.<br>
- South and East England, with a lower-medium average transaction price.<br>
- Industrial cities of the North (Manchester, Liverpool, Leeds), with a lower-medium average transaction price as well.</p>
</section>
<section id="zoom-on-london-1" class="level4">
<h4 class="anchored" data-anchor-id="zoom-on-london-1">Zoom on London</h4>
<p>Once more, it is interesting to zoom on the Greater London area. We don’t have data on the very central local authorities (too small) of Westminster (City of) and London (City of), but we see that the districts with the highest average price are the central ones, namely Kensington &amp; Chelsea (in yellow) and Camden (in green). It is also worth noting that as soon as you move apart from the center, the average price quickly becomes similar to the rest of England.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Up to this point, our analysis was mainly based on visual observation of our data. We decided to go a little further and try to see if we could use more advanced data science and statistical methods to corroborate our findings.</p>
</section>
</section>
<section id="a-little-machine-learning-science-clustering-in-theory" class="level3">
<h3 class="anchored" data-anchor-id="a-little-machine-learning-science-clustering-in-theory">A little machine learning science: clustering in theory</h3>
<p>This part of the analysis will use clustering to form several different groups (ie clusters) containing all the price of the transactions from 1995 to 2023. Then, we will do a geographical analysis of those clusters and see if the areas sharing a lot of transactions in the same clusters also share common characteristics.</p>
<p>Mainly, clustering aims at partitioning the data into distinct groups so that the observations within each group are quite similar to each other, and data in different groups are quite different from each other. To do so, we will use K-means clustering, ie we partition the data into a pre-specified number of clusters.</p>
<p>K-means clustering consists into partitioning the data such that within cluster variation is a small as possible, ie we want to solve the problem:</p>
<p><span class="math display">\[ \quad \textrm{minimize}_{~~C_1,...,C_K}\quad\sum_{k=1}^{K} WCW(C_k) \quad(1) \]</span> Where <span class="math inline">\(WCW(C_k)\)</span> denotes the within cluster variation for cluster <span class="math inline">\(C_k\)</span>, and is defined using Squared Euclidean distance:</p>
<p><span class="math display">\[WCW(C_k) = \frac{1}{|n_k|}\sum_{i,i'\in C_k}\sum_{j=1}^{p}(x_{ij}-x_{i'j})^2 \]</span> Where <span class="math inline">\(n_k\)</span> denotes the number of observations in cluster the <span class="math inline">\(k\)</span>th cluster.</p>
<p>In practice, the K-means clustering algorithm randomly allocates a number from 1 to <span class="math inline">\(K\)</span> to each of the observations, forming randomly K initial clusters. Then it iterates a procedure that consists in calculating the centroid for each cluster, and then allocate each point to the cluster whose centroid is the closer in terms of Squared Euclidean distance, until we reach a stable assignment of observations in each clusters.</p>
<p>Because the initial assignment is random, repeating the procedure can yield different results, and we need to specify the number of times the K-means must be done. Eventually, we keep the result of the K-means clustering with the lowest (1).</p>
</section>
<section id="clustering-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="clustering-in-practice">Clustering in practice</h3>
<p>To recap, first, each transaction has been assigned to a cluster based on its price. Then we associated each local authority level with the corresponding cluster mode (ie, the most frequent cluster in all transactions that took places in this specific local authority). Finally, we draw a map associating each local authority to the average transaction price in the cluster (ie, the centroid).</p>
<section id="country-level-1" class="level4">
<h4 class="anchored" data-anchor-id="country-level-1">Country level</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We obtain very similar results with the clustering method, leading us to confirm our previous analysis in terms of spatial distribution of prices. More precisely, we observe: - High prices around London.&nbsp; - Moderate prices in the East, the South and the industrial North.&nbsp; - Low prices in the Midlands and at the border with Scotland.&nbsp;</p>
</section>
<section id="zoom-on-london-2" class="level4">
<h4 class="anchored" data-anchor-id="zoom-on-london-2">Zoom on London</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Once more, results are quite similar with the ones from the previous section with very high prices in the centre of London, high prices in the first circle and prices close to the national average when going a little further.</p>
</section>
</section>
<section id="socio-demographics-of-clusters" class="level3">
<h3 class="anchored" data-anchor-id="socio-demographics-of-clusters">Socio-demographics of clusters</h3>
<p>In the previous part, we showed that clusters matched with the geographical distribution of average transaction prices. We are now interested in the socio-demographic determinants of real estate transactions.</p>
<p>We stayed at the local authority level and looked at both the average population and average income in each cluster. Since our data on income levels started in 2011, we took the mean income over the 2011-2021 period. The results can be seen in the table below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 38%">
<col style="width: 27%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Cluster</th>
<th style="text-align: right;">Average transaction price</th>
<th style="text-align: right;">Average population</th>
<th style="text-align: right;">Average income</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">54696</td>
<td style="text-align: right;">198144.9</td>
<td style="text-align: right;">35300.05</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">112410</td>
<td style="text-align: right;">172056.1</td>
<td style="text-align: right;">39892.45</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">169765</td>
<td style="text-align: right;">167045.0</td>
<td style="text-align: right;">45638.66</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">234735</td>
<td style="text-align: right;">175651.5</td>
<td style="text-align: right;">55264.35</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">394798</td>
<td style="text-align: right;">116020.0</td>
<td style="text-align: right;">NaN</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">664833</td>
<td style="text-align: right;">143940.0</td>
<td style="text-align: right;">60003.81</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">894678</td>
<td style="text-align: right;">116020.0</td>
<td style="text-align: right;">NaN</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The main conclusion we can draw from this new perspective, and it should not come as a surprise, the higher the transaction price, the higher the average income in the cluster. The size (in terms if population) of the local authorities does not seem to have a great impact on the clustering, and therefore on the prices.</p>
</section>
</section>
<section id="wrapping-up-spatiotemporal-patterns" class="level2">
<h2 class="anchored" data-anchor-id="wrapping-up-spatiotemporal-patterns">Wrapping-up: spatiotemporal patterns</h2>
<p>While the first section was devoted to the temporal analysis of prices and number of transactions, the second focused solely on the geographical distribution of our key variables. This third and last section will explore the combination of those two aspects.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-30-1.gif" class="img-fluid"></p>
</div>
</div>
<p>This first animated map summaries perfectly what we have seen so far. First, there is a large discrepancy in the distribution of the number of real estate transactions at the country level. Second, the sub-prime crisis of 2008 and the COVID-19 crisis had a huge impact on the number of transactions.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="uk_real_estate_files/figure-html/unnamed-chunk-32-1.gif" class="img-fluid"></p>
</div>
</div>
<p>While this last figure is interesting as it shows that the main driver to the evolution of nominal prices is indeed time, it is important to remember that both geographical and temporal effects are playing at the same time. In fact, we see that the map shifts from dark blues to light greens and yellow (temporal effect), but, this shift starts from London, then spreads to the regions around London, then to the industrial North and finally to the rest of the UK (geographical effect).</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>What are the main findings of our analysis?</p>
<ul>
<li><p>We find strong evidence of a seasonality pattern in the registered number of real estate transactions each year. There is two distinct periods: an high seasonal trend from June to September that could be explained by the fact that most families try to move in their new homes during the summer holidays such that their children do not have to change school in the middle of the year, and a low seasonal trend between December and January.</p></li>
<li><p>The evolution of the number of transactions over longer periods of time can also be analysed through the movement of the bank rate. We find that what really matters is less the level of the bank rate than its direction, as people may still contract an loan to buy real estate in an high bank rate environment if they expect this rate to remain constant in the next years, and conversely if they expect a decrease.</p></li>
<li><p>The Covid-19 and the post pandemic periods are associated with an overall increase in the volatility of the prices and the number of transactions.</p></li>
<li><p>The most attractive regions in terms of the number of transactions per inhabitant are the ones on the coasts and the less attractive ones are the regions around Wales and the Northern territories.</p></li>
<li><p>When looking at the prices, we can regroup the UK in 4 main regions according to the average transaction:&nbsp;</p></li>
<li><p>The greater London area, with the highest average transaction price.<br>
</p></li>
<li><p>Midlands and Wales, with the lowest average transaction price.<br>
</p></li>
<li><p>South and East England, with a lower-medium average transaction price.<br>
</p></li>
<li><p>Industrial cities of the North (Manchester, Liverpool, Leeds), with a lower-medium average transaction price as well.</p></li>
</ul>
<p>When we apply clustering techniques to the transaction data, we find corroborating evidence as we observe:</p>
<ul>
<li><p>High prices around London.&nbsp;</p></li>
<li><p>Moderate prices in the East, the South and the industrial North.&nbsp;</p></li>
<li><p>Low prices in the Midlands and at the border with Scotland.&nbsp;</p></li>
<li><p>Over a long period, the main driver to the evolution of nominal prices is time, through inflation and a correlated increase of the nominal prices.</p></li>
</ul>
</section>
<section id="appendix" class="level1">
<h1>Appendix</h1>
<section id="data-loading" class="level2">
<h2 class="anchored" data-anchor-id="data-loading">Data loading</h2>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning">Data cleaning</h2>
</section>
<section id="data-exporting" class="level2">
<h2 class="anchored" data-anchor-id="data-exporting">Data exporting</h2>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>